[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Optional: lock Node version used by Netlify build image
[build.environment]
  NODE_VERSION = "20"
